print("SYÖTÄ HENKILÖTIEDOT")
print("-------------------")
print()
etunimet = input("Anna etunimet: ")
sukunimi = input("Anna sukunimi: ")
puhelinnumero = input("Anna puhelinnumero: ")
sposti = input("Anna sähköpostiosoite: ")
osoite = input("Anna lähiosoite: ")
pnumero = input("Anna postinumero: ")
kaupunki = input("Anna kaupunki: ")
maa = input("Anna maa: ")
vuosi = input("Anna syntymävuosi: ")
print()
print("KIITOS!")
